baseURL = 'https://scottross.dev/'
languageCode = 'en-us'
title = '/home/scott'
theme = 'smol'

[menu]  
  [[menu.main]]
        identifier = "start"
        name = "~/"
        url = "/"
        weight = 1


  [[menu.main]]
        identifier = "posts"
        name = "~/posts"
        url = "/posts/"
        weight = 2

  [[menu.main]]
        identifier = "tags"
        name = "~/tags"
        url = "/tags/"
        weight = 3

  [[menu.main]]
        identifier = "prviacy"
        name = "~/privacy"
        url = "/privacy/"
        weight = 4

# Footer
  [[menu.footer]]
        name = "github"
        url = "https://github.com/scottross123"
        weight = 1

    [[menu.footer]]
        name = "gitlab"
        url = "https://example.com/@user"
        weight = 2
