aseURL = 'https://scottross.dev/'
languageCode = 'en-us'
title = '/home/scott'
theme = 'smol'

enableGitInfo = true
sectionPagesMenu = 'places'
showChildrenInMenu = true

[menu]  
  [[menu.main]]
        identifier = "posts"
        name = "~/posts"
        url = "/posts/"
        weight = 20

  [[menu.main]]
        identifier = "docs"
        name = "~/docs"
        url = "/docs/"
        weight = 30

  [[menu.main]]
        identifier = "tags"
        name = "~/tags"
        url = "/tags/"
        weight = 60

  [[menu.main]]
        identifier = "analytics"
        name = "~/analytics"
        url = "/analytics/"
        weight = 70

# Footer
  [[menu.footer]]
        name = "github"
        url = "https://github.com/scottross123"
        weight = 1

    [[menu.footer]]
        name = "gitlab"
        url = "https://gitlab.com/swr2112"
        weight = 2

    [[menu.footer]]
        name = "rss"
        url = "/blog/index.xml"
        weight = 3

[outputs]
home = ['html']
section = ['html']
taxonomy = ['html']
term = ['html', 'rss']
