baseURL = 'https://scottross.dev/'
languageCode = 'en-us'
title = '/home/scott'
theme = 'smol'

[menu]  
  [[menu.main]]
        identifier = "start"
        name = "~/"
        url = "/"
        weight = 1

  [[menu.main]]
        identifier = "about"
        name = "~/about"
        url = "/about/"
        weight = 2

  [[menu.main]]
        identifier = "posts"
        name = "~/posts"
        url = "/posts/"
        weight = 3

  [[menu.main]]
        identifier = "tags"
        name = "~/tags"
        url = "/tags/"
        weight = 4

  [[menu.main]]
        identifier = "prviacy"
        name = "~/privacy"
        url = "/privacy/"
        weight = 5

# Footer
  [[menu.footer]]
        name = "github"
        url = "https://github.com/scottross123"
        weight = 1

    [[menu.footer]]
        name = "gitlab"
        url = "https://gitlab.com/swr2112"
        weight = 2

    [[menu.footer]]
        name = "rss"
        url = "/posts/index.xml"
        weight = 3

[outputs]
home = ['html']
section = ['html']
taxonomy = ['html']
term = ['html', 'rss']